### PR TITLE
Give access to the dual solution of the master to the user

### LINKED ISSUE #591: Access to dual value of constraints of the master problem
Hello,

I would like to access the duals associated with the constraints in the master problem for a separate model, and it seems like I can't if they are added as lazy constraints. (I could be completely wrong about this, but I did not see a solution when looking into the topic.) 

Would it be possible to iteratively add constraints to the master problem without the use of lazy constraints, perhaps something similar to @constraint() in JuMP? 

Thank you so much!

### PR DESCRIPTION
**Pull request by guimarqu**
fix #591

### CODE REVIEW

File: src/Algorithm/colgen.jl [hunk 1]
```diff
@@ -691,6 +690,11 @@ function cg_main_loop!(
             lp_bound = get_lp_primal_bound(rm_optstate) + getvalue(partial_solution)
             set_lp_primal_bound!(cg_optstate, lp_bound)
 
+            dual_rm_sol = get_best_lp_dual_sol(rm_optstate)
+            if dual_rm_sol !== nothing
+                set_lp_dual_sol!(cg_optstate, dual_rm_sol)
```
Comment (rrsadykov) [inline src/Algorithm/colgen.jl:695]: Is it really necessary to set the primal and dual solution to `cg_optstate` on every column generation iteration? May be ne may do it only at the end of column generation to save time?

File: src/Algorithm/treesearch.jl [hunk 2]
```diff
@@ -88,6 +88,7 @@ mutable struct TreeSearchRuntimeData{Sense}
     Sense::Type{<:Coluna.AbstractSense}
     conquer_units_to_restore::UnitsUsage
     worst_db_of_pruned_node::DualBound{Sense}
+    worst_dual_sol_of_pruned_node::Union{Nothing,DualSolution}
```
Comment (rrsadykov) [inline src/Algorithm/treesearch.jl:91]: I do not understand the purpose of `worst_db_of_pruned_node` and `worst_dual_sol_of_pruned_node`. Why do we need that? Normally, the current dual bound of TreeSearch is computed as the worst dual bound of open nodes.

**Review by rrsadykov — CHANGES_REQUESTED** [review]
For me, the top algorithm should return only one OptimizationState which contains the best found IP solution and possibly the LP primal and dual solutions for the root (this may be parameterized to save time).

File: src/Algorithm/treesearch.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (guimarqu) [reply src/Algorithm/treesearch.jl]: I don't know why I did that.

File: src/optimize.jl [hunk 3]
```diff
@@ -110,6 +110,13 @@ function optimize!(
         add_lp_primal_sol!(outstate, proj_cols_on_rep(lp_primal_sol, master))
     end
 
+    # lp_dual_sol to retrieve, for instance, the dual value of generated cuts
+    # TODO: how to project the master dual solution on the original formulation ?
```
[the remark this answers is not in the document]
Comment (guimarqu) [reply src/optimize.jl]: Ok for me.

File: src/optimize.jl [hunk 4]
```diff
@@ -110,6 +110,13 @@ function optimize!(
...
+    lp_dual_sol = get_best_lp_dual_sol(algstate)
```
[the remark this answers is not in the document]
Comment (guimarqu) [reply src/optimize.jl:114]: Ok, I had doubts about what I did and what you suggest, so let's return the dual solution found at the root node.

File: src/Algorithm/colgen.jl (hunk 1 above)
Comment (guimarqu) [reply src/Algorithm/colgen.jl:695]: I don't think it will change anything for performances. It's just a pointer that you put in the optimisation state.

File: src/Algorithm/treesearch.jl [hunk 5]
```diff
@@ -308,31 +309,25 @@ function updatedualbound!(data::TreeSearchRuntimeData)
...
         db = get_ip_dual_bound(getoptstate(node))
-        sol = get_best_lp_dual_sol(getoptstate(sol))
         if isbetter(worst_bound, db)
             worst_bound = db
-            worst_sol = sol
         end
     end
+
     if isbetter(worst_bound, data.worst_db_of_pruned_node)
         worst_bound = data.worst_db_of_pruned_node
```
Comment (rrsadykov) [inline src/Algorithm/treesearch.jl:327]: I still do not understand why dual bound of the tree search takes into account dual bounds of pruned nodes? It should be just equal to the worst dual bound of open nodes (or to the primal bound if there are no open nodes)

**Review by rrsadykov — CHANGES_REQUESTED** [review]

File: src/Algorithm/treesearch.jl (hunk 5 above)
Comment (guimarqu) [reply src/Algorithm/treesearch.jl:327]: This is something that we should address in a separate PR. I neither don't understand why I did that.

Comment (rrsadykov) [reply src/Algorithm/treesearch.jl:327]: Why separate PR? This is critical issue. It should be addressed before the next release.

Comment (guimarqu) [reply src/Algorithm/treesearch.jl:327]: Because this is not the scope of this PR. There is no rush for the next release.

**Review by rrsadykov — APPROVED** [review]
