### PR TITLE
Fix wrong duty for setupvar in master coeff matrix

### LINKED ISSUE #314: DwSpSetupVar in master
**Describe the bug**
DwSpSetupVar variable in the master

**To Reproduce**
Dantzig-Wolfe decomposition

**Expected behavior**
Should be a representant

### PR DESCRIPTION
**Pull request by guimarqu**
Fix #314

### CODE REVIEW

File: src/MathProg/decomposition.jl [hunk 1]
```diff
@@ -169,7 +169,7 @@ function create_side_vars_constrs!(
             rhs = lb_mult, kind = Core, sense = Greater, inc_val = 100.0
         )
         masterform.parent_formulation.dw_pricing_sp_lb[spuid] = getid(lb_conv_constr)
-        coefmatrix[getid(lb_conv_constr), getid(setupvar)] = 1.0
```
Comment (guimarqu) [inline src/MathProg/decomposition.jl:172]: The duty of the id in the coefficient matrix of the master was DwSetupVar instead of MasterRepPricingSetupVar.
