### PR TITLE
Delete buffer changes when removing variable or constraint

### LINKED ISSUE #489: Invalid variable index
**Describe the bug**
When using Coluna to solve my application I get the following error after some nodes of the branch-and-price tree:

`ERROR: LoadError: The index MathOptInterface.VariableIndex(-1) is invalid. Note that an index becomes invalid after it has been deleted.`

I am using the default `TreeSearchAlgorithm` params except that Primal Heuristics are disabled.

**To Reproduce**
Coluna parameters are set as follows:
```julia
coluna = optimizer_with_attributes(
        Coluna.Optimizer,
        "params" => Coluna.Params(
            solver = Coluna.Algorithm.TreeSearchAlgorithm(
                conqueralg = Coluna.Algorithm.ColCutGenConquer(
                    primal_heuristics = Coluna.Algorithm.ParameterisedHeuristic[])
            )
        ),
        "default_optimizer" => Gurobi.Optimizer
    )
```

**Expected behavior**
```console
ERROR: LoadError: The index MathOptInterface.VariableIndex(-1) is invalid. Note that an index becomes invalid after it has been deleted.
Stacktrace:
 [1] _info(::Gurobi.Optimizer, ::MathOptInterface.VariableIndex) at C:\Users\hugoh\.julia\packages\Gurobi\qk7lG\src\MOI_wrapper.jl:654
 [2] column at C:\Users\hugoh\.julia\packages\Gurobi\qk7lG\src\MOI_wrapper.jl:665 [inlined]
 [3] modify(::Gurobi.Optimizer, ::MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}}, ::MathOptInterface.ScalarCoefficientChan
ge{Float64}) at C:\Users\hugoh\.julia\packages\Gurobi\qk7lG\src\MOI_wrapper.jl:3087
 [4] update_cost_in_optimizer!(::Coluna.MathProg.Formulation{Coluna.MathProg.DwMaster}, ::Coluna.MathProg.Variable) at C:\Users\hugoh\.julia\packages\Coluna\u
QdsR\src\MathProg\MOIinterface.jl:49
 [5] sync_solver!(::Coluna.MathProg.MoiOptimizer, ::Coluna.MathProg.Formulation{Coluna.MathProg.DwMaster}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\
MathProg\optimizerwrappers.jl:70
 [6] optimize_with_moi!(::Coluna.MathProg.MoiOptimizer, ::Coluna.MathProg.Formulation{Coluna.MathProg.DwMaster}, ::Coluna.Algorithm.OptimizationState{Coluna.M
athProg.Formulation{Coluna.MathProg.DwMaster},Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\basic\solveipform.jl:137
 [7] optimize_lp_form!(::Coluna.Algorithm.SolveLpForm, ::Coluna.MathProg.MoiOptimizer, ::Coluna.MathProg.Formulation{Coluna.MathProg.DwMaster}, ::Coluna.Algor
ithm.OptimizationState{Coluna.MathProg.Formulation{Coluna.MathProg.DwMaster},Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Alg
orithm\basic\solvelpform.jl:50
 [8] macro expansion at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\basic\solvelpform.jl:73 [inlined]
 [9] macro expansion at C:\Users\hugoh\.julia\packages\TimerOutputs\4QAIk\src\TimerOutput.jl:190 [inlined]
 [10] run!(::Coluna.Algorithm.SolveLpForm, ::Coluna.Env, ::Coluna.Algorithm.ModelData, ::Coluna.Algorithm.OptimizationInput{Coluna.MathProg.Formulation{Coluna
.MathProg.DwMaster},Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\basic\solvelpform.jl:58
 [11] macro expansion at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\colgen.jl:654 [inlined]
 [12] macro expansion at .\timing.jl:233 [inlined]
 [13] cg_main_loop!(::Coluna.Algorithm.ColumnGeneration, ::Coluna.Env, ::Int64, ::Coluna.Algorithm.OptimizationState{Coluna.MathProg.Formulation{Coluna.MathPr
og.DwMaster},Coluna.MathProg.MinSense}, ::Coluna.Algorithm.ReformData) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\colgen.jl:650
 [14] run!(::Coluna.Algorithm.ColumnGeneration, ::Coluna.Env, ::Coluna.Algorithm.ReformData, ::Coluna.Algorithm.OptimizationInput{Coluna.MathProg.Formulation{
Coluna.MathProg.DwMaster},Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\colgen.jl:97
 [15] run!(::Coluna.Algorithm.ColCutGenConquer, ::Coluna.Env, ::Coluna.Algorithm.ReformData, ::Coluna.Algorithm.ConquerInput) at C:\Users\hugoh\.julia\package
s\Coluna\uQdsR\src\Algorithm\conquer.jl:170
 [16] apply_conquer_alg_to_node!(::Coluna.Algorithm.Node, ::Coluna.Algorithm.ColCutGenConquer, ::Coluna.Env, ::Coluna.Algorithm.ReformData, ::Dict{Tuple{Colun
a.ColunaBase.AbstractModel,Pair{DataType,DataType}},Coluna.Algorithm.UnitAccessMode}, ::Float64, ::Float64) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src
\Algorithm\conquer.jl:61
 [17] run_conquer_algorithm!(::Coluna.Algorithm.TreeSearchAlgorithm, ::Coluna.Env, ::Coluna.Algorithm.TreeSearchRuntimeData{Coluna.MathProg.MinSense}, ::Colun
a.Algorithm.ReformData, ::Coluna.Algorithm.Node) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\treesearch.jl:252
 [18] run!(::Coluna.Algorithm.TreeSearchAlgorithm, ::Coluna.Env, ::Coluna.Algorithm.ReformData, ::Coluna.Algorithm.OptimizationInput{Coluna.MathProg.Formulati
on{Coluna.MathProg.DwMaster},Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\Algorithm\treesearch.jl:330
 [19] optimize!(::Coluna.MathProg.Reformulation, ::Coluna.Env, ::Coluna.ColunaBase.Bound{Coluna.MathProg.Primal,Coluna.MathProg.MinSense}, ::Coluna.ColunaBase
.Bound{Coluna.MathProg.Dual,Coluna.MathProg.MinSense}) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\optimize.jl:98
 [20] macro expansion at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\optimize.jl:65 [inlined]
 [21] macro expansion at C:\Users\hugoh\.julia\packages\TimerOutputs\4QAIk\src\TimerOutput.jl:190 [inlined]
 [22] optimize!(::Coluna.MathProg.Problem, ::Coluna.Annotations, ::Coluna.Params) at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\optimize.jl:64
 [23] optimize! at C:\Users\hugoh\.julia\packages\Coluna\uQdsR\src\MOIwrapper.jl:101 [inlined]
 [24] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{Coluna.Optimizer}) at C:\Users\hugoh\.julia\packages\MathOptInterface\ZJFKw\src\Bridges\bridge_
optimizer.jl:264
 [25] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface
.Utilities.Model{Float64}}}) at C:\Users\hugoh\.julia\packages\MathOptInterface\ZJFKw\src\Utilities\cachingoptimizer.jl:215
 [26] optimize!(::JuMP.Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple
{(),Tuple{}}}) at C:\Users\hugoh\.julia\packages\JuMP\y5vgk\src\optimizer_interface.jl:139
 [27] optimize!(::JuMP.Model) at C:\Users\hugoh\.julia\packages\BlockDecomposition\OYIcC\src\BlockDecomposition.jl:51
 [28] optimize!(::JuMP.Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple
{(),Tuple{}}}) at C:\Users\hugoh\.julia\packages\JuMP\y5vgk\src\optimizer_interface.jl:129
 [29] optimize! at C:\Users\hugoh\.julia\packages\JuMP\y5vgk\src\optimizer_interface.jl:115 [inlined] (repeats 2 times)
 [30] macro expansion at C:\Users\hugoh\Documents\Codes\Atoptima\UFPB_Project\ColunaBenchmarks\src\CapacitatedLotSizing\run.jl:31 [inlined]
 [31] macro expansion at .\timing.jl:233 [inlined]
 [32] run_clsp(::String, ::Main.CapacitatedLotSizing.AppParams) at C:\Users\hugoh\Documents\Codes\Atoptima\UFPB_Project\ColunaBenchmarks\src\CapacitatedLotSiz
ing\run.jl:30
 [33] top-level scope at C:\Users\hugoh\Documents\Codes\Atoptima\UFPB_Project\ColunaBenchmarks\src\CapacitatedLotSizing\scripts\runsingleinstance.jl:13
 [34] include(::Function, ::Module, ::String) at .\Base.jl:380
 [35] include(::Module, ::String) at .\Base.jl:368
 [36] exec_options(::Base.JLOptions) at .\client.jl:296
 [37] _start() at .\client.jl:506
in expression starting at C:\Users\hugoh\Documents\Codes\Atoptima\UFPB_Project\ColunaBenchmarks\src\CapacitatedLotSizing\scripts\runsingleinstance.jl:13
```

**Environment:**
 - Julia version 1.5.3
 - OS: Windows 10 64 bits
 - Coluna version 0.3.7

### PR DESCRIPTION
**Pull request by laradicp**
close #489 

- [X] Variable cost
- [X] Variable kind
- [X] Variable lb
- [X] Variable ub
- [X] Constraint rhs
- [x] Matrix coefficient

### CODE REVIEW

File: src/MathProg/optimizerwrappers.jl [hunk 1]
```diff
@@ -118,6 +118,8 @@ function sync_solver!(optimizer::MoiOptimizer, f::Formulation)
     for ((c_id, v_id), coeff) in buffer.reset_coeffs
         # Ignore modifications involving vc's that were removed
         (c_id in buffer.constr_buffer.removed || v_id in buffer.var_buffer.removed) && continue
+        iscuractive(f, c_id)&&iscuractive(f, v_id) || continue
+        isexplicit(f, c_id)&&isexplicit(f, v_id) || continue
```
Comment (guimarqu) [inline src/MathProg/optimizerwrappers.jl:122]:
```suggestion
        iscuractive(f, c_id) && isexplicit(f, c_id) || continue
        iscuractive(f, v_id) && isexplicit(f, v_id) || continue
```

We always check if a constraint or a variable is active and explicit so it's better if we keep this informal convention here

**Review by guimarqu — APPROVED** [review]
