### PR TITLE
Leave conquer if colgen prunes node

### LINKED ISSUE #520: Branching is performed when a node is infeasible
**Describe the bug**
When a node is declared infeasible, branching is nevertheless performed 

**To Reproduce**
This can be reproduced for example in the test "play gap" by using this data file

```
2 7
8 5 11 21 6 5 19 
1 12 11 12 14 8 5 
6 3 3 1 2 1 1 
9 1 1 3 1 5 4 
5 8 
```

and by removing or commenting `BD.objectiveprimalbound!(model, 100)`

**Expected behaviour**

Extract of the output:

```
***************************************************************************************
**** BaB tree root node
**** Local DB = 0.0000, global bounds : [ 0.0000 , Inf ], time = 0.00 sec.
***************************************************************************************
  <it=  1> <et= 0.00> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=    0.0000> <mlp=70000.0000> <PB=Inf>
  <it=  2> <et= 0.01> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=    0.0000> <mlp=10093.0000> <PB=Inf>
  <it=  3> <et= 0.01> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=    0.0000> <mlp=10079.0000> <PB=Inf>
  <it=  4> <et= 0.02> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=10033.0000> <mlp=10070.0000> <PB=Inf>
  <it=  5> <et= 0.02> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=10034.7500> <mlp=10059.5000> <PB=Inf>
  <it=  6> <et= 0.03> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=10034.7500> <mlp=10059.5000> <PB=Inf>
  <it=  7> <et= 0.03> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=10050.5000> <mlp=10059.5000> <PB=Inf>
  <it=  8> <et= 0.03> <mst= 0.00> <sp= 0.00> <cols= 1> <al= 0.00> <DB=10052.0000> <mlp=10056.0000> <PB=Inf>
  <it=  9> <et= 0.04> <mst= 0.00> <sp= 0.00> <cols= 0> <al= 0.00> <DB=10056.0000> <mlp=10056.0000> <PB=Inf>
[ Info: Column generation algorithm has converged.
# <it=  1> <et= 0.04> <mst= 0.00> <sp= 0.00> <cols= 0> <al= 0.00> <DB=10000.0000> <mlp=10000.0000> <PB=Inf>
[ Info: Phase one determines infeasibility.
[ Info: Running Restricted Master IP heuristic
┌ Warning: Solver has no result to show.
└ @ Coluna.Algorithm ~/.julia/dev/Coluna/src/Algorithm/basic/solveipform.jl:130
No primal solution found. Termination status is INFEASIBLE. 
***************************************************************************************
**** BaB tree node N° 2, parent N° 1, depth 1, 2 open nodes
**** Local DB = 10000.0000, global bounds : [ 10000.0000 , Inf ], time = 0.05 sec.
**** Branching constraint: x[1,2]>=1.0
***************************************************************************************
  <it=  1> <et= 0.05> <mst= 0.00> <sp= 0.00> <cols= 2> <al= 0.00> <DB=       Inf> <mlp=10073.0000> <PB=Inf>
```

**Environment (please complete the following information):**
master branch with Julia 1.4 and Mac OS

### PR DESCRIPTION
**Pull request by guimarqu**
close #520

### CODE REVIEW

File: src/Algorithm/conquer.jl [hunk 1]
```diff
@@ -204,46 +204,48 @@ function run!(algo::ColCutGenConquer, env::Env, data::ReformData, input::Conquer
...
-    heuristics_to_run = Tuple{AbstractOptimizationAlgorithm, String, Float64}[]
-    for heuristic in algo.primal_heuristics
-        #TO DO : get_tree_order of nodes in strong branching is always -1
-        if getdepth(node) <= heuristic.max_depth && 
-            mod(get_tree_order(node) - 1, heuristic.frequency) == 0
-            push!(heuristics_to_run, (
-                heuristic.algorithm, heuristic.name,
-                isrootnode(node) ? heuristic.root_priority : heuristic.nonroot_priority
-            ))
+    if !node_pruned
```
Comment (rrsadykov) [inline src/Algorithm/conquer.jl:207]: I do not understand why adding this check allows to avoid the bug.

**Review by rrsadykov — APPROVED** [review]
Ok, I have got it

File: src/Algorithm/conquer.jl (hunk 1 above)
Comment (guimarqu) [reply src/Algorithm/conquer.jl:207]: Because otherwise it was loosing the infeasibility status returned by colgen and was considering the node unpruned. As a result, the node termination status was OTHER_LIMIT and branching was then performed.
