### PR TITLE
Robust essential cut (lazy constraint) generation

### LINKED ISSUE #450: How to use Coluna along with Lazy constraints ?
Hello,

I'm trying to use Coluna on my relaxed model (some constraints are not in the initial model, but it's still an MILP) along with MOI.LazyConstraint from JuMP.

I construct my model as following : 

` coluna = optimizer_with_attributes(Coluna.Optimizer,"params" => Coluna.Params(solver = Coluna.Algorithm.TreeSearchAlgorithm()),"default_optimizer" => CPLEX.Optimizer) `
and then  
`my_model = BlockModel(coluna)`

After creating all variables and constraints, I have the callback function 
`              function my_lazy_constraint_callback(cb_data)
`

And finally, add it to my model as following : 
`    MOI.set(my_model, MOI.LazyConstraintCallback(), my_lazy_constraint_callback)       
`

So, when I call _optimize!(my_model)_, I get the following error : 

> MathOptInterface.UnsupportedAttribute{MathOptInterface.LazyConstraintCallback}: Attribute MathOptInterface.LazyConstraintCallback() is not supported by the model.
Stacktrace:
 [1] #throw_set_error_fallback#14(::MathOptInterface.SetAttributeNotAllowed{MathOptInterface.LazyConstraintCallback}, ::typeof(MathOptInterface.throw_set_error_fallback), ::Coluna.Optimizer, ::MathOptInterface.LazyConstraintCallback, ::Function) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/attributes.jl:386
 [2] throw_set_error_fallback(::Coluna.Optimizer, ::MathOptInterface.LazyConstraintCallback, ::Function) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/attributes.jl:383
 [3] set(::Coluna.Optimizer, ::MathOptInterface.LazyConstraintCallback, ::Function) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/attributes.jl:372
 [4] set(::MathOptInterface.Bridges.LazyBridgeOptimizer{Coluna.Optimizer}, ::MathOptInterface.LazyConstraintCallback, ::Function) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Bridges/bridge_optimizer.jl:593
 [5] _pass_attributes(::MathOptInterface.Bridges.LazyBridgeOptimizer{Coluna.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::Bool, ::MathOptInterface.Utilities.IndexMap, ::Array{MathOptInterface.AbstractModelAttribute,1}, ::Tuple{}, ::Tuple{}, ::Tuple{}, ::typeof(MathOptInterface.set)) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/copy.jl:148
 [6] pass_attributes at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/copy.jl:112 [inlined]
 [7] pass_attributes at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/copy.jl:111 [inlined]
 [8] default_copy_to(::MathOptInterface.Bridges.LazyBridgeOptimizer{Coluna.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::Bool) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/copy.jl:337
 [9] #automatic_copy_to#113 at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/copy.jl:15 [inlined]
 [10] #automatic_copy_to at ./none:0 [inlined]
 [11] #copy_to#3 at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Bridges/bridge_optimizer.jl:268 [inlined]
 [12] (::getfield(MathOptInterface, Symbol("#kw##copy_to")))(::NamedTuple{(:copy_names,),Tuple{Bool}}, ::typeof(MathOptInterface.copy_to), ::MathOptInterface.Bridges.LazyBridgeOptimizer{Coluna.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}) at ./none:0
 [13] attach_optimizer(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/cachingoptimizer.jl:149
 [14] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /home/wesley/.julia/packages/MathOptInterface/bygN7/src/Utilities/cachingoptimizer.jl:185
 [15] #optimize!#97(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(optimize!), ::Model, ::Nothing) at /home/wesley/.julia/packages/JuMP/CZ8vV/src/optimizer_interface.jl:131
 [16] #optimize! at ./none:0 [inlined] (repeats 2 times)
 [17] optimize!(::Model) at /home/wesley/.julia/packages/BlockDecomposition/OYIcC/src/BlockDecomposition.jl:51
 [18] #optimize!#97(::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(optimize!), ::Model, ::Nothing) at /home/wesley/.julia/packages/JuMP/CZ8vV/src/optimizer_interface.jl:121
 [19] optimize! at /home/wesley/.julia/packages/JuMP/CZ8vV/src/optimizer_interface.jl:107 [inlined] (repeats 2 times)
 [20] create_COLUNA(::Instance, ::Parameters) at /raid/home/wesley/Doc/Codes/DW_Decom/include/NSDP_solver.ipynb:In[2]:529
 [21] top-level scope at In[85]:10

It works fine if I build my model without using Coluna :  _my_model =Model(CPLEX.Optimizer)_.
So, I'd like to know if it is possible to use Coluna along with Lazy Constraint-based callbacks.

Thank you in advance.

Wesley

### PR DESCRIPTION
**Pull request by guimarqu**
Essential cut gen is performed :

- [x] in the cut callback algorithm
- [x] each time the colgen algorithm finds an integer solution
- [x] after heuristic

for colgen : when the cut violates the solution, the colgen restarts at phase 3 if it was at phase 3 and at phase 1 if it was at phase ~1 or~ 2

fix #450

### CODE REVIEW

**Comment by guimarqu** [comment]
I think it's wrong, it should restart at phase 2 in colgen because it never does essential cutgen at phase 1. I'll fix tomorrow.

File: src/Algorithm/colgen.jl [hunk 1]
```diff
@@ -700,7 +718,7 @@ function cg_main_loop!(
             if nb_new_col < 0
                 @error "Infeasible subproblem."
                 setterminationstatus!(cg_optstate, INFEASIBLE)
-                return true
+                return true, false
```
Comment (rrsadykov) [inline src/Algorithm/colgen.jl:721]: Is there a way to make it explicit here what "true" means and what "false" means (to increase the code readability)

File: src/Algorithm/colgen.jl [hunk 2]
```diff
@@ -661,13 +667,25 @@ function cg_main_loop!(
...
+            lp_bound = get_lp_primal_bound(rm_optstate) + getvalue(partial_solution)
+            set_lp_primal_bound!(cg_optstate, lp_bound)
 
             if phase != 1 && !contains(rm_sol, varid -> isanArtificialDuty(getduty(varid)))
-                if isinteger(proj_cols_on_rep(rm_sol, masterform))       
-                    update_ip_primal_sol!(cg_optstate, cat(rm_sol, partial_solution))
+                proj_sol = proj_cols_on_rep(rm_sol, masterform)
+                if isinteger(proj_sol) && isbetter(lp_bound, get_ip_primal_bound(cg_optstate))
+                    # Essential cut generation mandatory when colgen finds a feasible solution
+                    cutgen = CutCallbacks(call_robust_facultative = false)
```
Comment (rrsadykov) [inline src/Algorithm/colgen.jl:679]: Colgen should indicate that it uses another child algorithm (CutCallbacks) here:

`function get_child_algorithms(algo::ColumnGeneration, reform::Reformulation) `

Moreover, it would be nice if we indicate this only if at least one lazy cut callback is defined.
For this, I suggest to transform CutCallbacks to CutCallback which separates only one family of cuts. CutCallback would now whether it is lazy or facultative and its priority. Then every algorithm which uses cut separation (ColCutGenConquer and ColumnGeneration) should have a vector of CutCallback as a parameter. Then, there will be no overhead if no cut callbacks are defined. And it would be more flexible as priorities would allow us to separate "light" cut before "heavy" ones using priorities

**Review by rrsadykov — CHANGES_REQUESTED** [review]

File: src/Algorithm/colgen.jl (hunk 1 above)
Comment (guimarqu) [reply src/Algorithm/colgen.jl:721]: Ok I'm going to add a comment to describe the method.

File: src/Algorithm/colgen.jl (hunk 2 above)
Comment (guimarqu) [reply src/Algorithm/colgen.jl:679]: Ok for the first point. I'll fix. 

The second point sounds good, but it's a quite big refactoring so let's do it after we stabilize architecture of algorithms (you can open an issue with a link to your comment).

**Review by rrsadykov — APPROVED** [review]
