### PR TITLE
Optimality tolerance depending on the algorithm

### LINKED ISSUE #370: Bug with low optimality tolerance
Node is not cut by bound when column generation is stopped with the gap less than optimality tolerance.

To reproduce, run test "gap with all phases in col.gen" with optimality_tol = 1e-5.

### PR DESCRIPTION
**Pull request by guimarqu**
Fix #370

- Conquer algorithm returns `OPTIMAL` if the node is pruned, `OTHER_LIMIT` otherwise. 
- Add absolute & relative optimality tolerances in `ColumnGeneration`
- New methods `lp_gap_closed` and `ip_gap_closed` to check convergence with opt tolerances as kw arguments.

### CODE REVIEW

File: src/Algorithm/treesearch.jl [hunk 1]
```diff
@@ -279,64 +290,52 @@ function updatedualbound!(data::TreeSearchRuntimeData)
...
+        # dual bound of the optstate only at the root node.
+        run_conquer_algorithm!(algo, tsdata, rfdata, node)
+       
+        if getterminationstatus(node.optstate) == OPTIMAL || ip_gap_closed(node.optstate) # TODO tolerance of the TreeSearch
+            println("Node is already conquered. No children will be generated.")
+        else
+            run_divide_algorithm!(algo, tsdata, rfdata, node)
         end
+
+        updatedualbound!(tsdata)
```
Comment (rrsadykov) [inline src/Algorithm/treesearch.jl:310]: The dual bound calculation of the tree search algorithm should be corrected: the dual bound cannot be better than the worst dual bound of pruned nodes. The latter value should be stored and updated in the tree search data.

Comment (guimarqu) [reply src/Algorithm/treesearch.jl:310]: yes

File: src/Algorithm/conquer.jl [hunk 2]
```diff
@@ -150,7 +150,10 @@ function run!(algo::ColCutGenConquer, data::ReformData, input::ConquerInput)
     colgen_output = run!(algo.colgen, data, OptimizationInput(nodestate))
     update!(nodestate, getoptstate(colgen_output))
 
-    while !to_be_pruned(node) && nb_tightening_rounds < algo.max_nb_cut_rounds
+    subproblem_pruned = getterminationstatus(nodestate) == INFEASIBLE ||
+        ip_gap_closed(nodestate, atol = algo.colgen.opt_atol, rtol = algo.colgen.opt_rtol)
```
[the remark this answers is not in the document]
Comment (guimarqu) [reply src/Algorithm/conquer.jl]: I changed like you said and I put a TODO comment in the parameters of the algorithm.

**Review by rrsadykov — APPROVED** [review]
